#!/usr/bin/env bash
#using IFS while loop
#
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo "The user $f1's is part of the $f4's gang, lives in $f6's and rides $f7's. $f3's place is protected by the passcode $f2's, more info about the user here: $f5's"
done < "/etc/passwd"
