#!/usr/bin/env bash
#managing processes

start() 
{
	echo "manage_my_process started"
}
stop()
{
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart()
{
	kill manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process
	touch /var/run/my_process.pid > "$BASHPID"
	echo "manage_my_process restarted"
}
	case "$1" in
	start) start ;;
	stop)  stop;;
	*) echo "Usage: manage_my_process {start|stop|restart}" >&3
		exit 1
		;;
esac
