#!/usr/bin/env bash
#managing processes

start() 
{
	echo "manage_my_process started"
}
stop()
{
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
}
restart()
{
	case "$1" in
   start) start ;;
   stop)  stop;;
   *) echo "usage $0 start|stop" >&2
      exit 1
      ;;
esac
