#!/usr/bin/env bash
#managing processes

start() 
{
	echo "manage_my_process started" >> /var/run/my_process.pid
	echo "$PID"
}
stop()
{
	stop manage_my_process
	rm /var/run/my_process.pid && echo "manage_my_process stopped"
}
restart()
{
	kill manage_my_process
	rm /var/run/my_process.pid
	restart  manage_my_process
	echo "manage_my_process restarted" >> /var/run/my_process.pid
	echo "$PID"
}
	case "$1"  in
	start) 
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}";;
esac
