#!/usr/bin/env bash
#write a bash script that stops 4 process
pkill -f 4-to_infinity_and_beyond
~                                                                                                   
~                                                                                                   
~                                       
